#!/bin/python
import sys, getopt, time, datetime, calendar

#section 1 polytime
#get time now
minutes = int(time.time()%86400/60)
now = datetime.datetime.utcnow()
#print("It is now " + str(minutes) + " minutes since midnight UTC")

#wake config
wakeconf = []

for i in range(1, len(sys.argv), 2):
	dict = {'name': sys.argv[i], 'time': int(sys.argv[i+1])}
	wakeconf.append(dict)

wakeconf.sort(key=lambda k: k['time'])

#get polytime
polytime = 0
gapname = ''

if minutes < wakeconf[0]['time']:
	polytime = 1440 + minutes - wakeconf[-1]['time']
	gapname = wakeconf[-1]['name']

	
if int(polytime/60) == 0:
	polytimeout = str(polytime) + ' ' + gapname
else:
	polytimeout = str(int(polytime/60)) + ':' + str(polytime%60).zfill(2) + ' ' + gapname

#section 2 polydate
#timestamp of month's day 1
monthfirstday = now.replace(day=1,hour=0,minute=0,second=0,microsecond=0)
timestamp = calendar.timegm(monthfirstday.timetuple())

#number of arcs since midnight that day
for i in range(0,len(wakeconf)*32):
	if int(time.time()) >= timestamp + wakeconf[i%len(wakeconf)]['time']*60:
		timestamp +=  wakeconf[i%len(wakeconf)]['time']*60
		arcseq=i+1
	else:
		break

#month = now.strftime('%Y-%m-')


print("Arc " + str(arcseq).zfill(2) + ', ' + polytimeout)

